"""empty message

Revision ID: 7b026cc4f19d
Revises: 
Create Date: 2017-06-10 04:28:43.867000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b026cc4f19d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('serialnumber', sa.String(length=50), nullable=True),
    sa.Column('modelnumber', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freelancers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('hire_rate', sa.String(length=10), nullable=True),
    sa.Column('tel', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancers_first_name'), 'freelancers', ['first_name'], unique=False)
    op.create_index(op.f('ix_freelancers_hire_rate'), 'freelancers', ['hire_rate'], unique=False)
    op.create_index(op.f('ix_freelancers_job'), 'freelancers', ['job'], unique=False)
    op.create_index(op.f('ix_freelancers_last_name'), 'freelancers', ['last_name'], unique=False)
    op.create_index(op.f('ix_freelancers_tel'), 'freelancers', ['tel'], unique=False)
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('tel', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_address'), 'guests', ['address'], unique=False)
    op.create_index(op.f('ix_guests_first_name'), 'guests', ['first_name'], unique=False)
    op.create_index(op.f('ix_guests_job'), 'guests', ['job'], unique=False)
    op.create_index(op.f('ix_guests_last_name'), 'guests', ['last_name'], unique=False)
    op.create_index(op.f('ix_guests_tel'), 'guests', ['tel'], unique=False)
    op.create_index(op.f('ix_guests_title'), 'guests', ['title'], unique=False)
    op.create_table('lives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('service_provided', sa.String(length=30), nullable=True),
    sa.Column('sat', sa.String(length=50), nullable=True),
    sa.Column('ul', sa.String(length=30), nullable=True),
    sa.Column('dl', sa.String(length=30), nullable=True),
    sa.Column('sr', sa.String(length=30), nullable=True),
    sa.Column('fec', sa.String(length=30), nullable=True),
    sa.Column('mod', sa.String(length=30), nullable=True),
    sa.Column('access', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=40), nullable=True),
    sa.Column('time_gmt_s', sa.String(length=30), nullable=True),
    sa.Column('time_gmt_e', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('reg_code', sa.String(length=10), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('actual_s_time', sa.String(length=30), nullable=True),
    sa.Column('actual_e_time', sa.String(length=30), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('service_provided', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('space', sa.String(length=50), nullable=True),
    sa.Column('time_gmt_s', sa.String(length=30), nullable=True),
    sa.Column('time_gmt_e', sa.String(length=30), nullable=True),
    sa.Column('extension', sa.String(length=30), nullable=True),
    sa.Column('actual_s_time', sa.String(length=30), nullable=True),
    sa.Column('actual_e_time', sa.String(length=30), nullable=True),
    sa.Column('duration', sa.String(length=30), nullable=True),
    sa.Column('engineer', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=40), nullable=True),
    sa.Column('guest', sa.String(length=30), nullable=True),
    sa.Column('transport_company', sa.String(length=30), nullable=True),
    sa.Column('transport_kind', sa.String(length=50), nullable=True),
    sa.Column('camera', sa.String(length=50), nullable=True),
    sa.Column('cameraman', sa.String(length=50), nullable=True),
    sa.Column('car', sa.Boolean(), nullable=True),
    sa.Column('ratecard', sa.String(length=200), nullable=True),
    sa.Column('extrafees', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sngorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=20), nullable=True),
    sa.Column('engineer', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=20), nullable=True),
    sa.Column('time_gmt_s', sa.String(length=30), nullable=True),
    sa.Column('time_gmt_e', sa.String(length=30), nullable=True),
    sa.Column('cameraman', sa.String(length=50), nullable=True),
    sa.Column('tech', sa.String(length=50), nullable=True),
    sa.Column('driver', sa.String(length=50), nullable=True),
    sa.Column('camera', sa.String(length=50), nullable=True),
    sa.Column('car', sa.String(length=30), nullable=True),
    sa.Column('extrafees', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=20), nullable=True),
    sa.Column('showname', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=20), nullable=True),
    sa.Column('time_gmt_s', sa.String(length=30), nullable=True),
    sa.Column('time_gmt_e', sa.String(length=30), nullable=True),
    sa.Column('guest_counter', sa.String(length=3), nullable=True),
    sa.Column('guest1', sa.String(length=30), nullable=True),
    sa.Column('guest2', sa.String(length=30), nullable=True),
    sa.Column('guest3', sa.String(length=30), nullable=True),
    sa.Column('guest4', sa.String(length=30), nullable=True),
    sa.Column('guest5', sa.String(length=30), nullable=True),
    sa.Column('guest6', sa.String(length=30), nullable=True),
    sa.Column('guest7', sa.String(length=30), nullable=True),
    sa.Column('guest8', sa.String(length=30), nullable=True),
    sa.Column('guest9', sa.String(length=30), nullable=True),
    sa.Column('guest10', sa.String(length=30), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=20), nullable=True),
    sa.Column('guest_counter', sa.String(length=3), nullable=True),
    sa.Column('guest1', sa.String(length=30), nullable=True),
    sa.Column('guest2', sa.String(length=30), nullable=True),
    sa.Column('guest3', sa.String(length=30), nullable=True),
    sa.Column('guest4', sa.String(length=30), nullable=True),
    sa.Column('guest5', sa.String(length=30), nullable=True),
    sa.Column('guest6', sa.String(length=30), nullable=True),
    sa.Column('guest7', sa.String(length=30), nullable=True),
    sa.Column('guest8', sa.String(length=30), nullable=True),
    sa.Column('guest9', sa.String(length=30), nullable=True),
    sa.Column('guest10', sa.String(length=30), nullable=True),
    sa.Column('city1', sa.String(length=20), nullable=True),
    sa.Column('city2', sa.String(length=20), nullable=True),
    sa.Column('city3', sa.String(length=20), nullable=True),
    sa.Column('city4', sa.String(length=20), nullable=True),
    sa.Column('city5', sa.String(length=20), nullable=True),
    sa.Column('city6', sa.String(length=20), nullable=True),
    sa.Column('city7', sa.String(length=20), nullable=True),
    sa.Column('city8', sa.String(length=20), nullable=True),
    sa.Column('city9', sa.String(length=20), nullable=True),
    sa.Column('city10', sa.String(length=20), nullable=True),
    sa.Column('ways', sa.String(length=30), nullable=True),
    sa.Column('uberfees', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.String(length=60), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('tel', sa.String(length=60), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_heng', sa.Boolean(), nullable=True),
    sa.Column('is_acc', sa.Boolean(), nullable=True),
    sa.Column('is_sat', sa.Boolean(), nullable=True),
    sa.Column('is_eng', sa.Boolean(), nullable=True),
    sa.Column('is_mos', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_hire_date'), 'employees', ['hire_date'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_salary'), 'employees', ['salary'], unique=False)
    op.create_index(op.f('ix_employees_tel'), 'employees', ['tel'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_tel'), table_name='employees')
    op.drop_index(op.f('ix_employees_salary'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_hire_date'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('transports')
    op.drop_table('studios')
    op.drop_table('sngorders')
    op.drop_table('reports')
    op.drop_table('lives')
    op.drop_index(op.f('ix_guests_title'), table_name='guests')
    op.drop_index(op.f('ix_guests_tel'), table_name='guests')
    op.drop_index(op.f('ix_guests_last_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_job'), table_name='guests')
    op.drop_index(op.f('ix_guests_first_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_address'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_freelancers_tel'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_last_name'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_job'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_hire_rate'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_first_name'), table_name='freelancers')
    op.drop_table('freelancers')
    op.drop_table('equipment')
    op.drop_table('departments')
    # ### end Alembic commands ###
